spring:
  application:
    name: dalston-config-server-git
  cloud:
    config:
      server:
        git:
          uri: https://github.com/chiminwon/config-repo-demo.git
          username: chiminwon@gmail.com
          password: 1qaz!QAZ
          skipSslValidation: true
          timeout: 5
          basedir:
#          uri: http://git.oschina.net/didispace/config-repo-demo/
#          uri: https://gitee.com/chiminwon/config-repo
#          search-paths: repo
#          username: chiminwon@gmail.com
#          password: 1qaz!QAZ
#        uri: git@github.com:chiminwon/config-repo-demo.git

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:1001/eureka,http://127.0.0.1:1002/eureka
server:
  port: 1501
