#spring:
#  application:
#    name: dalston-config-client-git
server:
  port: 1701
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:1001/eureka,http://127.0.0.1:1002/eureka
env: dev
